Added fully automated installation.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -35,117 +35,296 @@ Consult the README for further information.
 
 Options:
 
-  --help                    display this help message
+  --help , -h, -?           display this help message
+  --magedomain              Specify the shop domain (e.g. 1702.magentoshops.vm).
+                            The subdomain has to be the same string as --magename
+  --magename                The shop name which gets used for the URL, directory and database name.
+  --mageversion             Version of Magento to be used. Has to be one of
+                            [ce1501|ce1510|ce1600|ce1610|ce1620|ce1702]
+  --modman                  Whether you want modman to be initialized.
+                            [y|n]                            
   --usage                   display this help message
   --version                 display the version of this script
 
 Get more information at
-http://matthias-zeis.com"
+https://github.com/mzeis/MageSpawner"
 
 ###########################
 ## Common options: help, usage and version number
 
-if [ "$1" = "--help" ]; then
-  echo "$usage"
-  exit 0
-elif [ "$1" = "--usage" ]; then
-  echo "$usage"
-  exit 0
-elif [ "$1" = "--version" ]; then
-  echo "$version"
-  exit 0
-fi
+parse_arguments ()
+{
+    while :
+    do
+        case $1 in
+            -h | --help | --usage | -\?)
+                echo "$usage"
+                exit 0
+                ;;
+            --magedomain)
+                MAGE_SHOPDOMAIN=$2
+                shift 2
+                ;;
+            --magename)
+                MAGE_NAME=$2
+                shift 2
+                ;;
+            --mageversion)
+                MAGE_VERSION=$2
+                shift 2
+                ;;    
+            --modman)
+                MODMAN_USE=$2
+                shift 2
+                ;;
+            --version)
+                echo "$version"
+                exit 0
+                ;;
+            --) # End of all options
+                shift
+                break
+                ;;
+            -*)
+                echo "WARN: Unknown option (ignored): $1" >&2
+                shift
+                ;;
+            *)  # no more options. Stop while loop
+                break
+                ;;
+        esac
+    done
+    
+    return 0
+}
+
+###########################
+## Initialise the script: read configuration files, find executables etc.
+
+init_spawner ()
+{
+    if [[ ! -f ${0%/*}/config.conf ]]; then
+      echo -e >&2 'config.conf not found.\nPlease copy config.conf.sample to config.conf and adjust your settings.'
+      exit 1
+    fi
+    . ${0%/*}/config.conf
+    
+    if [[ $MAGE_BASE_DIR = "" || $MAGE_BASE_DIR = "/" ]]; then
+      echo >&2 "Base directory '$MAGE_BASE_DIR' is not allowed. Please change in configuration."
+      exit 1
+    fi
+    
+    MYSQL=$(command -v mysql) || { echo >&2 'MySQL executable not found'; exit 1; }
+    PHP=$(command -v php) || { echo >&2 'PHP executable not found'; exit 1; }
+    SED=$(command -v sed) || { echo >&2 'sed command not found'; exit 1; }
+    WGET=$(command -v wget)
+    CURL=$(command -v curl)
+    if [[ $WGET = "" && $CURL = "" ]]; then
+      echo >&2 'Neither wget nor curl command found. Please install wget or curl and re-run command.';
+      exit 1;
+    fi
+    if [[ $EUID -ne 0 ]]; then
+      CMDCHMOD="sudo chmod"
+      CMDCHOWN="sudo chown"
+    else
+      CMDCHMOD="chmod"
+      CMDCHOWN="chown"
+    fi
+    
+    echo -e 'Welcome to MageSpawner.\n'
+    
+    return 0
+}
+
+###########################
+## Get Magento download URL
+
+get_magento_download_url ()
+{
+    case "$1" in
+        ce1501)
+            MAGE_DOWNLOAD_URL="http://www.magentocommerce.com/downloads/assets/1.5.0.1/magento-1.5.0.1.tar.gz"
+            return 0;
+            ;;
+        ce1510)
+            MAGE_DOWNLOAD_URL="http://www.magentocommerce.com/downloads/assets/1.5.1.0/magento-1.5.1.0.tar.gz"
+            return 0;
+            ;;
+        ce1600)
+            MAGE_DOWNLOAD_URL="http://www.magentocommerce.com/downloads/assets/1.6.0.0/magento-1.6.0.0.tar.gz"
+            return 0;
+            ;;
+        ce1610)
+            MAGE_DOWNLOAD_URL="http://www.magentocommerce.com/downloads/assets/1.6.1.0/magento-1.6.1.0.tar.gz"
+            return 0;
+            ;;
+        ce1620)
+            MAGE_DOWNLOAD_URL="http://www.magentocommerce.com/downloads/assets/1.6.2.0/magento-1.6.2.0.tar.gz"
+            return 0;
+            ;;
+        ce1702)
+            MAGE_DOWNLOAD_URL="http://www.magentocommerce.com/downloads/assets/1.7.0.2/magento-1.7.0.2.tar.gz"
+            return 0;
+            ;;
+        *)
+            MAGE_DOWNLOAD_URL=""
+            return 1;
+            ;;
+    esac
+}
+
+###########################
+## Get Magento version
+
+get_magento_version ()
+{
+    MAGE_DOWNLOAD_URL=""
+    
+    if get_magento_download_url $MAGE_VERSION; then
+        return 0;
+    fi
+
+    echo "Which version do you want to install?"
+    echo "1) None, abort installation"
+    echo "2) CE 1.5.0.1"
+    echo "3) CE 1.5.1.0"
+    echo "4) CE 1.6.0.0"
+    echo "5) CE 1.6.1.0"
+    echo "6) CE 1.6.2.0"
+    echo "7) CE 1.7.0.2"
+    
+    while true; do
+       read -p "Enter the number (e.g. 1): " INPUT_MAGE_VERSION
+    
+       case "$INPUT_MAGE_VERSION" in
+          1)
+              echo "Aborting installation."
+              exit 0;
+              ;;
+          2)
+              echo -e "CE 1.5.0.1 selected.\n"
+              get_magento_download_url ce1501
+              break
+              ;;
+          3)
+              echo -e "CE 1.5.1.0 selected.\n"
+              get_magento_download_url ce1510
+              break
+              ;;
+          4)
+              echo -e "CE 1.6.0.0 selected.\n"
+              get_magento_download_url ce1600
+              break
+              ;;
+          5)
+              echo -e "CE 1.6.1.0 selected.\n"
+              get_magento_download_url ce1610
+              break
+              ;;
+          6)
+              echo -e "CE 1.6.2.0 selected.\n"
+              get_magento_download_url ce1620
+              break
+              ;;
+          7)
+              echo -e "CE 1.7.0.2 selected.\n"
+              get_magento_download_url ce1702
+              break
+              ;;
+          *)
+              echo -e "Invalid option, please try again.\n"
+              ;;
+        esac
+    done 
+    
+    return 0
+}
+
+###########################
+## Get Magento shop (= subdomain) name.
+
+get_mage_name ()
+{
+    if [[ -z "$MAGE_NAME" ]]; then
+        echo "Specify the shop name. It may be used for the URL, directory and database name, so don't use spaces, special characters or the like."
+        read -p "Shop name (default: ${MAGE_DEFAULT_NAME}): " MAGE_NAME
+        MAGE_NAME=${MAGE_NAME:-${MAGE_DEFAULT_NAME}}
+    fi
+    
+    return 0
+}
+
+###########################
+## Get the Magento shop domain.
+
+get_mage_domain ()
+{
+    if [[ -z "$MAGE_SHOPDOMAIN" ]]; then
+        MAGE_SHOPDOMAIN="${MAGE_NAME}.${MAGE_DOMAIN}"
+    fi
+    
+    return 0
+}
+
+###########################
+## Setup modman
+
+setup_modman ()
+{
+    if [[ -z "$MODMAN_USE" ]]; then
+        while true; do
+           read -p "Do you want to use modman? (y/n) " MODMAN_USE
+        
+           case "$MODMAN_USE" in
+              y)
+                MODMAN_USE="y"
+                break;;
+              n)
+                MODMAN_USE="n"
+                break;
+                ;;
+              *)
+                echo -e "Invalid command, please enter 'y' or 'n' (without quotes).\n"
+                ;;
+           esac
+        done
+    fi
+    
+    if [[ "$MODMAN_USE" != "y" ]]; then
+        return 0;
+    fi
+    
+    MODMAN_BIN=$(command -v modman)
+      
+    if [[ $MODMAN_BIN != "" ]]; then
+        modman init
+        echo ""
+    else
+        # if [[ $WGET != "" ]]; then
+        #   bash < <(wget -O - https://raw.github.com/colinmollenhour/modman/master/modman-installer)
+        # elif [[ $CURL != "" ]]; then
+        #   bash < <(curl -s https://raw.github.com/colinmollenhour/modman/master/modman-installer)
+        # fi
+        # source ~/.profile
+        echo 'Please install modman first: https://github.com/colinmollenhour/modman';
+        echo 'Then call "modman init" from the Magento root directory as this will not be executed now.';
+    fi 
+    
+    return 0
+}
 
 ###########################
 ## Main script
 
-echo -e 'Welcome to MageSpawner.\n'
+parse_arguments "$@"
 
-if [[ ! -f ${0%/*}/config.conf ]]; then
-  echo -e >&2 'config.conf not found.\nPlease copy config.conf.sample to config.conf and adjust your settings.'
-  exit 1
-fi
-. ${0%/*}/config.conf
+init_spawner
 
-if [[ $MAGE_BASE_DIR = "" || $MAGE_BASE_DIR = "/" ]]; then
-  echo >&2 "Base directory '$MAGE_BASE_DIR' is not allowed. Please change in configuration."
-  exit 1
-fi
+get_magento_version
 
-MYSQL=$(command -v mysql) || { echo >&2 'MySQL executable not found'; exit 1; }
-PHP=$(command -v php) || { echo >&2 'PHP executable not found'; exit 1; }
-SED=$(command -v sed) || { echo >&2 'sed command not found'; exit 1; }
-WGET=$(command -v wget)
-CURL=$(command -v curl)
-if [[ $WGET = "" && $CURL = "" ]]; then
-  echo >&2 'Neither wget nor curl command found. Please install wget or curl and re-run command.';
-  exit 1;
-fi
-if [[ $EUID -ne 0 ]]; then
-  CMDCHMOD="sudo chmod"
-  CMDCHOWN="sudo chown"
-else
-  CMDCHMOD="chmod"
-  CMDCHOWN="chown"
-fi
-echo "Which version do you want to install?"
-echo "1) None, abort installation"
-echo "2) CE 1.5.0.1"
-echo "3) CE 1.5.1.0"
-echo "4) CE 1.6.0.0"
-echo "5) CE 1.6.1.0"
-echo "6) CE 1.6.2.0"
-echo "7) CE 1.7.0.2"
+get_mage_name
 
-while true; do
-   read -p "Enter the number (e.g. 1): " MAGE_VERSION
-
-   case "$MAGE_VERSION" in
-      1)
-          echo "Aborting installation."
-          exit;
-          ;;
-      2)
-          echo -e "CE 1.5.0.1 selected.\n"
-          MAGE_DOWNLOAD_URL="http://www.magentocommerce.com/downloads/assets/1.5.0.1/magento-1.5.0.1.tar.gz"
-          break
-          ;;
-      3)
-          echo -e "CE 1.5.1.0 selected.\n"
-          MAGE_DOWNLOAD_URL="http://www.magentocommerce.com/downloads/assets/1.5.1.0/magento-1.5.1.0.tar.gz"
-          break
-          ;;
-      4)
-          echo -e "CE 1.6.0.0 selected.\n"
-          MAGE_DOWNLOAD_URL="http://www.magentocommerce.com/downloads/assets/1.6.0.0/magento-1.6.0.0.tar.gz"
-          break
-          ;;
-      5)
-          echo -e "CE 1.6.1.0 selected.\n"
-          MAGE_DOWNLOAD_URL="http://www.magentocommerce.com/downloads/assets/1.6.1.0/magento-1.6.1.0.tar.gz"
-          break
-          ;;
-      6)
-          echo -e "CE 1.6.2.0 selected.\n"
-          MAGE_DOWNLOAD_URL="http://www.magentocommerce.com/downloads/assets/1.6.2.0/magento-1.6.2.0.tar.gz"
-          break
-          ;;
-      7)
-          echo -e "CE 1.7.0.2 selected.\n"
-          MAGE_DOWNLOAD_URL="http://www.magentocommerce.com/downloads/assets/1.7.0.2/magento-1.7.0.2.tar.gz"
-          break
-          ;;
-      *)
-          echo -e "Invalid option, please try again.\n"
-          ;;
-    esac
-done 
-
-
-echo "Specify the shop name. It may be used for the URL, directory and database name, so don't use spaces, special characters or the like."
-read -p "Shop name (default: ${MAGE_DEFAULT_NAME}): " MAGE_NAME
-MAGE_NAME=${MAGE_NAME:-${MAGE_DEFAULT_NAME}}
-MAGE_SHOPDOMAIN="${MAGE_NAME}.${MAGE_DOMAIN}"
+get_mage_domain
 
 # Use information for setting variables
 MAGE_UNSECURE_URL="http://${MAGE_SHOPDOMAIN}"
@@ -196,36 +375,7 @@ $SED "s/#RewriteBase \/magento\//RewriteBase \//" ${MAGE_BASE_DIR}${MAGE_SHOPDOM
 rm .htaccess.backup
 echo -e ".htaccess edited.\n"
 
-while true; do
-   read -p "Do you want to use modman? (y/n) " MODMAN_USE
-
-   case "$MODMAN_USE" in
-      y)
-          MODMAN_BIN=$(command -v modman)
-          
-          if [[ $MODMAN_BIN != "" ]]; then
-              modman init
-              echo ""
-          else
-              # if [[ $WGET != "" ]]; then
-              #   bash < <(wget -O - https://raw.github.com/colinmollenhour/modman/master/modman-installer)
-              # elif [[ $CURL != "" ]]; then
-              #   bash < <(curl -s https://raw.github.com/colinmollenhour/modman/master/modman-installer)
-              # fi
-              # source ~/.profile
-              echo 'Please install modman first: https://github.com/colinmollenhour/modman';
-              echo 'Then call "modman init" from the Magento root directory as this will not be executed now.';
-          fi 
-          break;        
-          ;;
-      n)
-          break;
-          ;;
-      *)
-          echo -e "Invalid command, please enter 'y' or 'n' (without quotes).\n"
-          ;;
-    esac
-done
+setup_modman
 
 # Adjust permissions 
 echo "Final permission settings..."
